alter table properties add column if not exists additional_images text[] default '{}';
alter table properties add column if not exists living_rooms integer;
alter table properties add column if not exists kitchens integer;
alter table properties add column if not exists parking_spots integer default 0;
alter table properties add column if not exists furnished text default 'unfurnished';
alter table properties add column if not exists has_electricity boolean default false;
alter table properties add column if not exists has_water boolean default false;
alter table properties add column if not exists has_sewage boolean default false;
alter table properties add column if not exists has_gas boolean default false;
alter table properties add column if not exists amenities text[] default '{}';
alter table properties add column if not exists neighborhood text;
alter table properties add column if not exists map_zoom integer default 15;
alter table properties add column if not exists video_url text;
alter table properties add column if not exists virtual_tour_url text;
alter table properties add column if not exists nearby_places jsonb default '[]';
alter table properties add column if not exists owner_name text;
alter table properties add column if not exists owner_phone text;
alter table properties add column if not exists is_active boolean default true;
alter table properties add column if not exists inquiry_count integer default 0;
alter table properties add column if not exists property_number text;
alter table properties add column if not exists plot_number text;
alter table properties add column if not exists license_number text;
alter table properties add column if not exists land_area numeric(10,2);
alter table properties add column if not exists building_area numeric(10,2);
alter table clients add column if not exists national_id text;
alter table clients add column if not exists nationality text default 'سعودي';
alter table clients add column if not exists birth_date date;
alter table clients add column if not exists occupation text;
alter table clients add column if not exists budget_min numeric(15,2);
alter table clients add column if not exists budget_max numeric(15,2);
alter table clients add column if not exists preferred_property_types text[] default '{}';
alter table clients add column if not exists preferred_cities text[] default '{}';
alter table clients add column if not exists preferred_contact text default 'phone';
alter table clients add column if not exists is_blacklisted boolean default false;
alter table clients add column if not exists blacklist_reason text;
alter table clients add column if not exists tags text[] default '{}';
alter table clients add column if not exists last_contact timestamptz;
alter table clients add column if not exists assigned_to uuid;
alter table clients add column if not exists created_by uuid;
do $$ declare rec record; begin for rec in select policyname, tablename from pg_policies where schemaname = 'public' loop execute format('drop policy if exists %I on %I', rec.policyname, rec.tablename); end loop; end $$;
do $$ begin
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'properties') then execute 'create policy properties_all on properties for all using (true) with check (true)'; end if;
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'clients') then execute 'create policy clients_all on clients for all using (true) with check (true)'; end if;
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'inquiries') then execute 'create policy inquiries_all on inquiries for all using (true) with check (true)'; end if;
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'contracts') then execute 'create policy contracts_all on contracts for all using (true) with check (true)'; end if;
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'payments') then execute 'create policy payments_all on payments for all using (true) with check (true)'; end if;
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'appointments') then execute 'create policy appointments_all on appointments for all using (true) with check (true)'; end if;
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'activity_log') then execute 'create policy activity_log_all on activity_log for all using (true) with check (true)'; end if;
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'email_templates') then execute 'create policy email_templates_all on email_templates for all using (true) with check (true)'; end if;
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'currencies') then execute 'create policy currencies_all on currencies for all using (true) with check (true)'; end if;
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'favorites') then execute 'create policy favorites_all on favorites for all using (true) with check (true)'; end if;
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'tags') then execute 'create policy tags_all on tags for all using (true) with check (true)'; end if;
  if exists (select from pg_tables where schemaname = 'public' and tablename = 'notifications') then execute 'create policy notifications_all on notifications for all using (true) with check (true)'; end if;
end $$;
